"""Biens physiques: vivres, armes, matieres, outils, etc.

Plan du fichier:
01 - GOODS_CATALOG: constantes des biens d'inventaire.
02 - good_definition: recupere une definition de bien.
03 - base_good_prices: prix nationaux de base des biens.
"""

from copy import deepcopy


GOODS_CATALOG = {
 'vivres_secs': {'id': 'vivres_secs',
                 'label': 'Vivres séchées',
                 'type': 'bien',
                 'family': 'vivres',
                 'base_price': 0.3,
                 'weight': 1,
                 'utility': 100,
                 'fractionable': True,
                 'perishable': False,
                 'saturation': 'faible',
                 'production_place': '',
                 'savings_use': False},
 'vivres_frais': {'id': 'vivres_frais',
                  'label': 'Vivres fraîches',
                  'type': 'bien',
                  'family': 'vivres',
                  'base_price': 0.4,
                  'weight': 0.8,
                  'utility': 120,
                  'fractionable': True,
                  'perishable': True,
                  'saturation': 'faible',
                  'production_place': '',
                  'savings_use': False},
 'conserves': {'id': 'conserves',
               'label': 'Conserves',
               'type': 'bien',
               'family': 'vivres',
               'base_price': 0.6,
               'weight': 0.8,
               'utility': 110,
               'fractionable': True,
               'perishable': False,
               'saturation': 'faible',
               'production_place': '',
               'savings_use': False},
 'vivres_luxe': {'id': 'vivres_luxe',
                 'label': 'Vivres de luxe',
                 'type': 'bien',
                 'family': 'vivres',
                 'base_price': 1.2,
                 'weight': 0.8,
                 'utility': 180,
                 'fractionable': True,
                 'perishable': False,
                 'saturation': 'faible',
                 'production_place': '',
                 'savings_use': False},
 'sucre': {'id': 'sucre',
           'label': 'Sucre',
           'type': 'bien',
           'family': 'sucre',
           'base_price': 0.8,
           'weight': 1,
           'utility': 120,
           'fractionable': True,
           'perishable': False,
           'saturation': 'faible',
           'production_place': '',
           'savings_use': False},
 'confiserie': {'id': 'confiserie',
                'label': 'Confiserie',
                'type': 'bien',
                'family': 'sucre',
                'base_price': 1.5,
                'weight': 1,
                'utility': 220,
                'fractionable': True,
                'perishable': False,
                'saturation': 'moyenne',
                'production_place': '',
                'savings_use': False},
 'tabac': {'id': 'tabac',
           'label': 'Tabac',
           'type': 'bien',
           'family': 'tabac',
           'base_price': 0.8,
           'weight': 1,
           'utility': 120,
           'fractionable': True,
           'perishable': False,
           'saturation': 'faible',
           'production_place': '',
           'savings_use': False},
 'cafe': {'id': 'cafe',
          'label': 'Café',
          'type': 'bien',
          'family': 'boisson',
          'base_price': 0.7,
          'weight': 1,
          'utility': 110,
          'fractionable': True,
          'perishable': False,
          'saturation': 'faible',
          'production_place': '',
          'savings_use': False},
 'the': {'id': 'the',
         'label': 'Thé',
         'type': 'bien',
         'family': 'boisson',
         'base_price': 0.9,
         'weight': 1,
         'utility': 115,
         'fractionable': True,
         'perishable': False,
         'saturation': 'faible',
         'production_place': '',
         'savings_use': False},
 'cigarette': {'id': 'cigarette',
               'label': 'Cigarettes',
               'type': 'bien',
               'family': 'tabac',
               'base_price': 0.25,
               'weight': 1,
               'utility': 45,
               'fractionable': True,
               'perishable': False,
               'saturation': 'faible',
               'production_place': '',
               'savings_use': False},
 'cigare': {'id': 'cigare',
            'label': 'Cigare',
            'type': 'bien',
            'family': 'tabac',
            'base_price': 1.5,
            'weight': 1,
            'utility': 180,
            'fractionable': True,
            'perishable': False,
            'saturation': 'moyenne',
            'production_place': '',
            'savings_use': False},
 'whisky': {'id': 'whisky',
            'label': 'Whisky',
            'type': 'bien',
            'family': 'alcool',
            'base_price': 1.2,
            'weight': 1,
            'utility': 160,
            'fractionable': True,
            'perishable': False,
            'saturation': 'faible',
            'production_place': '',
            'savings_use': False},
 'gnole': {'id': 'gnole',
           'label': 'Gnôle',
           'type': 'bien',
           'family': 'alcool',
           'base_price': 0.6,
           'weight': 1,
           'utility': 110,
           'fractionable': True,
           'perishable': False,
           'saturation': 'faible',
           'production_place': '',
           'savings_use': False},
 'vin': {'id': 'vin',
         'label': 'Vin',
         'type': 'bien',
         'family': 'alcool',
         'base_price': 1.0,
         'weight': 1,
         'utility': 140,
         'fractionable': True,
         'perishable': False,
         'saturation': 'faible',
         'production_place': '',
         'savings_use': False},
 'cognac': {'id': 'cognac',
            'label': 'Cognac',
            'type': 'bien',
            'family': 'alcool',
            'base_price': 2.5,
            'weight': 1,
            'utility': 260,
            'fractionable': True,
            'perishable': False,
            'saturation': 'faible',
            'production_place': '',
            'savings_use': False},
 'bourbon': {'id': 'bourbon',
             'label': 'Bourbon',
             'type': 'bien',
             'family': 'alcool',
             'base_price': 1.6,
             'weight': 1,
             'utility': 190,
             'fractionable': True,
             'perishable': False,
             'saturation': 'faible',
             'production_place': '',
             'savings_use': False},
 'charbon': {'id': 'charbon',
             'label': 'Charbon',
             'type': 'bien',
             'family': 'combustibles',
             'base_price': 0.4,
             'weight': 1,
             'utility': 60,
             'fractionable': True,
             'perishable': False,
             'saturation': 0,
             'production_place': '',
             'savings_use': False},
 'fer': {'id': 'fer',
         'label': 'Fer',
         'type': 'bien',
         'family': 'materiau',
         'base_price': 0.8,
         'weight': 1,
         'utility': 80,
         'fractionable': True,
         'perishable': False,
         'saturation': 0,
         'production_place': '',
         'savings_use': False},
 'minerai_fer': {'id': 'minerai_fer',
                 'label': 'Minerai de fer',
                 'type': 'bien',
                 'family': 'minerai',
                 'base_price': 0.35,
                 'weight': 1,
                 'utility': 45,
                 'fractionable': True,
                 'perishable': False,
                 'saturation': 0,
                 'production_place': '',
                 'savings_use': False},
 'cuivre': {'id': 'cuivre',
            'label': 'Cuivre',
            'type': 'bien',
            'family': 'materiau',
            'base_price': 1.0,
            'weight': 1,
            'utility': 90,
            'fractionable': True,
            'perishable': False,
            'saturation': 0,
            'production_place': '',
            'savings_use': False},
 'minerai_cuivre': {'id': 'minerai_cuivre',
                    'label': 'Minerai de cuivre',
                    'type': 'bien',
                    'family': 'minerai',
                    'base_price': 0.45,
                    'weight': 1,
                    'utility': 50,
                    'fractionable': True,
                    'perishable': False,
                    'saturation': 0,
                    'production_place': '',
                    'savings_use': False},
 'nickel': {'id': 'nickel',
            'label': 'Nickel',
            'type': 'bien',
            'family': 'materiau',
            'base_price': 1.2,
            'weight': 1,
            'utility': 100,
            'fractionable': True,
            'perishable': False,
            'saturation': 0,
            'production_place': '',
            'savings_use': False},
 'minerai_nickel': {'id': 'minerai_nickel',
                    'label': 'Minerai de nickel',
                    'type': 'bien',
                    'family': 'minerai',
                    'base_price': 0.55,
                    'weight': 1,
                    'utility': 55,
                    'fractionable': True,
                    'perishable': False,
                    'saturation': 0,
                    'production_place': '',
                    'savings_use': False},
 'or': {'id': 'or',
        'label': 'Or',
        'type': 'bien',
        'family': 'materiau',
        'base_price': 20,
        'weight': 1,
        'utility': 2500,
        'fractionable': True,
        'perishable': False,
        'saturation': 0,
        'production_place': '',
        'savings_use': False},
 'minerai_or': {'id': 'minerai_or',
                'label': "Minerai d'or",
                'type': 'bien',
                'family': 'minerai',
                'base_price': 10,
                'weight': 1,
                'utility': 1200,
                'fractionable': True,
                'perishable': False,
                'saturation': 0,
                'production_place': '',
                'savings_use': False},
 'argent': {'id': 'argent',
            'label': 'Argent',
            'type': 'bien',
            'family': 'materiau',
            'base_price': 8,
            'weight': 1,
            'utility': 1200,
            'fractionable': True,
            'perishable': False,
            'saturation': 0,
            'production_place': '',
            'savings_use': False},
 'minerai_argent': {'id': 'minerai_argent',
                    'label': "Minerai d'argent",
                    'type': 'bien',
                    'family': 'minerai',
                    'base_price': 4,
                    'weight': 1,
                    'utility': 600,
                    'fractionable': True,
                    'perishable': False,
                    'saturation': 0,
                    'production_place': '',
                    'savings_use': False},
 'acier': {'id': 'acier',
           'label': 'Acier',
           'type': 'bien',
           'family': 'materiau',
           'base_price': 1.4,
           'weight': 1,
           'utility': 130,
           'fractionable': True,
           'perishable': False,
           'saturation': 0,
           'production_place': '',
           'savings_use': False},
 'bois': {'id': 'bois',
          'label': 'Bois',
          'type': 'bien',
          'family': 'materiau',
          'base_price': 0.3,
          'weight': 1,
          'utility': 60,
          'fractionable': True,
          'perishable': False,
          'saturation': 0,
          'production_place': '',
          'savings_use': False},
 'planche': {'id': 'planche',
             'label': 'Planche',
             'type': 'bien',
             'family': 'materiau',
             'base_price': 0.5,
             'weight': 1,
             'utility': 90,
             'fractionable': True,
             'perishable': False,
             'saturation': 0,
             'production_place': '',
             'savings_use': False},
 'bois_chauffage': {'id': 'bois_chauffage',
                    'label': 'Bois de chauffage',
                    'type': 'bien',
                    'family': 'combustibles',
                    'base_price': 0.25,
                    'weight': 1,
                    'utility': 70,
                    'fractionable': True,
                    'perishable': False,
                    'saturation': 0,
                    'production_place': '',
                    'savings_use': False},
 'charbon_bois': {'id': 'charbon_bois',
                  'label': 'Charbon de bois',
                  'type': 'bien',
                  'family': 'combustibles',
                  'base_price': 0.45,
                  'weight': 1,
                  'utility': 85,
                  'fractionable': True,
                  'perishable': False,
                  'saturation': 0,
                  'production_place': '',
                  'savings_use': False},
 'laine': {'id': 'laine',
           'label': 'Laine',
           'type': 'bien',
           'family': 'textile',
           'base_price': 0.8,
           'weight': 1,
           'utility': 90,
           'fractionable': True,
           'perishable': False,
           'saturation': 0,
           'production_place': '',
           'savings_use': False},
 'coton': {'id': 'coton',
           'label': 'Coton',
           'type': 'bien',
           'family': 'textile',
           'base_price': 0.6,
           'weight': 1,
           'utility': 80,
           'fractionable': True,
           'perishable': False,
           'saturation': 0,
           'production_place': '',
           'savings_use': False},
 'soie': {'id': 'soie',
          'label': 'Soie',
          'type': 'bien',
          'family': 'textile',
          'base_price': 3,
          'weight': 1,
          'utility': 220,
          'fractionable': True,
          'perishable': False,
          'saturation': 0,
          'production_place': '',
          'savings_use': False},
 'tissu': {'id': 'tissu',
           'label': 'Tissu',
           'type': 'bien',
           'family': 'textile',
           'base_price': 1,
           'weight': 1,
           'utility': 100,
           'fractionable': True,
           'perishable': False,
           'saturation': 0,
           'production_place': '',
           'savings_use': False},
 'outils': {'id': 'outils',
            'label': 'Outils',
            'type': 'bien',
            'family': 'outil',
            'base_price': 2,
            'weight': 1,
            'utility': 250,
            'fractionable': True,
            'perishable': False,
            'saturation': 0,
            'production_place': '',
            'savings_use': False},
 'explosifs': {'id': 'explosifs',
               'label': 'Explosifs',
               'type': 'bien',
               'family': 'outil',
               'base_price': 4,
               'weight': 1,
               'utility': 600,
               'fractionable': True,
               'perishable': False,
               'saturation': 0,
               'production_place': '',
               'savings_use': False},
 'papier': {'id': 'papier',
            'label': 'Papier',
            'type': 'bien',
            'family': 'papier',
            'base_price': 0.4,
            'weight': 1,
            'utility': 60,
            'fractionable': True,
            'perishable': False,
            'saturation': 0,
            'production_place': '',
            'savings_use': False},
 'journal': {'id': 'journal',
             'label': 'Journal',
             'type': 'bien',
             'family': 'information',
             'base_price': 0.1,
             'weight': 1,
             'utility': 40,
             'fractionable': True,
             'perishable': False,
             'saturation': 0,
             'production_place': '',
             'savings_use': False},
 'livre': {'id': 'livre',
           'label': 'Livre',
           'type': 'bien',
           'family': 'information',
           'base_price': 2,
           'weight': 1,
           'utility': 350,
           'fractionable': False,
           'perishable': False,
           'saturation': 'unique',
           'production_place': '',
           'savings_use': True},
 'engrais': {'id': 'engrais',
             'label': 'Engrais',
             'type': 'bien',
             'family': 'agriculture',
             'base_price': 0.5,
             'weight': 1,
             'utility': 120,
             'fractionable': True,
             'perishable': False,
             'saturation': 0,
             'production_place': '',
             'savings_use': False},
 'haillon': {'id': 'haillon',
             'label': 'Haillon',
             'type': 'bien',
             'family': 'habillement',
             'base_price': 0.2,
             'weight': 1,
             'utility': 20,
             'fractionable': False,
             'perishable': False,
             'saturation': 0,
             'production_place': '',
             'savings_use': True},
 'habit_travail': {'id': 'habit_travail',
                   'label': 'Habit de travail',
                   'type': 'bien',
                   'family': 'habillement',
                   'base_price': 2,
                   'weight': 1,
                   'utility': 180,
                   'fractionable': False,
                   'perishable': False,
                   'saturation': 'unique',
                   'production_place': '',
                   'savings_use': True},
 'habit_ordinaire': {'id': 'habit_ordinaire',
                     'label': 'Habit ordinaire',
                     'type': 'bien',
                     'family': 'habillement',
                     'base_price': 4,
                     'weight': 1,
                     'utility': 320,
                     'fractionable': False,
                     'perishable': False,
                     'saturation': 'unique',
                     'production_place': '',
                     'savings_use': True},
 'habit_elegant': {'id': 'habit_elegant',
                   'label': 'Habit élégant',
                   'type': 'bien',
                   'family': 'habillement',
                   'base_price': 12,
                   'weight': 1,
                   'utility': 900,
                   'fractionable': False,
                   'perishable': False,
                   'saturation': 'unique',
                   'production_place': '',
                   'savings_use': True},
 'manteau': {'id': 'manteau',
             'label': 'Manteau',
             'type': 'bien',
             'family': 'habillement',
             'base_price': 6,
             'weight': 1,
             'utility': 500,
             'fractionable': False,
             'perishable': False,
             'saturation': 'unique',
             'production_place': '',
             'savings_use': True},
 'cache_poussiere': {'id': 'cache_poussiere',
                     'label': 'Cache-poussière',
                     'type': 'bien',
                     'family': 'habillement',
                     'base_price': 8,
                     'weight': 1,
                     'utility': 650,
                     'fractionable': False,
                     'perishable': False,
                     'saturation': 'unique',
                     'production_place': '',
                     'savings_use': True},
 'fut_biere': {'id': 'fut_biere',
               'label': 'Fût de bière',
               'type': 'bien',
               'family': 'alcool',
               'base_price': 10,
               'weight': 5,
               'utility': 80,
               'fractionable': True,
               'perishable': False,
               'saturation': 0,
               'production_place': '',
               'savings_use': False},
 'colt_navy': {'id': 'colt_navy',
               'label': 'Colt navy',
               'type': 'bien',
               'family': 'arme_courte',
               'base_price': 15,
               'weight': 1,
               'utility': 800,
               'fractionable': False,
               'perishable': False,
               'saturation': 'unique',
               'production_place': '',
               'savings_use': True},
 'fusil_springfield': {'id': 'fusil_springfield',
                       'label': 'Fusil springfield',
                       'type': 'bien',
                       'family': 'arme_longue',
                       'base_price': 9,
                       'weight': 4,
                       'utility': 400,
                       'fractionable': False,
                       'perishable': False,
                       'saturation': 'unique',
                       'production_place': '',
                       'savings_use': True},
 'carabine_spencer': {'id': 'carabine_spencer',
                      'label': 'Carabine spencer',
                      'type': 'bien',
                      'family': 'arme_longue',
                      'base_price': 32,
                      'weight': 3,
                      'utility': 2000,
                      'fractionable': False,
                      'perishable': False,
                      'saturation': 'unique',
                      'production_place': '',
                      'savings_use': True},
 'materiel_prospection': {'id': 'materiel_prospection',
                          'label': 'Matériel de prospection',
                          'type': 'bien',
                          'family': 'outil',
                          'base_price': 5,
                          'weight': 6,
                          'utility': 800,
                          'fractionable': False,
                          'perishable': False,
                          'saturation': 0,
                          'production_place': '',
                          'savings_use': False},
 'plantes_medicinales': {'id': 'plantes_medicinales',
                         'label': 'Plantes médicinales',
                         'type': 'bien',
                         'family': 'medecine',
                         'base_price': 0.5,
                         'weight': 0.2,
                         'utility': 50,
                         'fractionable': False,
                         'perishable': True,
                         'saturation': 'moyenne',
                         'production_place': '',
                         'savings_use': False},
 'bandage': {'id': 'bandage',
             'label': 'Bandage',
             'type': 'bien',
             'family': 'medecine',
             'base_price': 0.5,
             'weight': 0.2,
             'utility': 80,
             'fractionable': False,
             'perishable': False,
             'saturation': 0,
             'production_place': '',
             'savings_use': False},
 'remede': {'id': 'remede',
            'label': 'Remède',
            'type': 'bien',
            'family': 'medecine',
            'base_price': 5,
            'weight': 0.5,
            'utility': 100,
            'fractionable': False,
            'perishable': False,
            'saturation': 'elevee',
            'production_place': '',
            'savings_use': True}}


def good_definition(good_id):
    return deepcopy(GOODS_CATALOG[good_id])


def base_good_prices():
    return {good_id: data["base_price"] for good_id, data in GOODS_CATALOG.items()}
