"""Services consommables: biere, repas, soins, bain, hotesse, coupe, etc.

Plan du fichier:
01 - SERVICE_CATALOG: constantes des services.
02 - service_definition: recupere une definition de service.
03 - service_default_price: prix par defaut d'un service.
04 - service_base_utility: utilite de base d'un service.
"""

from copy import deepcopy


SERVICE_CATALOG = {'biere': {'id': 'biere',
           'label': 'Bière',
           'type': 'service',
           'family': 'alcool',
           'base_price': 0.5,
           'weight': 0,
           'utility': 40,
           'fractionable': True,
           'perishable': False,
           'saturation': 'faible',
           'production_place': '',
           'savings_use': False},
 'repas': {'id': 'repas',
           'label': 'Repas',
           'type': 'service',
           'family': 'vivres',
           'base_price': 1,
           'weight': 0,
           'utility': 0,
           'fractionable': True,
           'perishable': False,
           'saturation': 'moyenne',
           'production_place': '',
           'savings_use': False},
 'bain': {'id': 'bain',
          'label': 'Bain',
          'type': 'service',
          'family': 'confort',
          'base_price': 0.5,
          'weight': 0,
          'utility': 30,
          'fractionable': False,
          'perishable': False,
          'saturation': 'elevee',
          'production_place': '',
          'savings_use': False},
 'chambre': {'id': 'chambre',
             'label': 'Chambre',
             'type': 'service',
             'family': 'logement',
             'base_price': 2,
             'weight': 0,
             'utility': 160,
             'fractionable': False,
             'perishable': False,
             'saturation': 'elevee',
             'production_place': '',
             'savings_use': False},
 'hotesse': {'id': 'hotesse',
             'label': 'Hôtesse',
             'type': 'service',
             'family': 'vice',
             'base_price': 2,
             'weight': 0,
             'utility': 110,
             'fractionable': True,
             'perishable': False,
             'saturation': 'elevee',
             'production_place': '',
             'savings_use': True},
 'coupe': {'id': 'coupe',
           'label': 'Coupe',
           'type': 'service',
           'family': 'confort',
           'base_price': 0.25,
           'weight': 0,
           'utility': 20,
           'fractionable': False,
           'perishable': False,
           'saturation': 'elevee',
           'production_place': '',
           'savings_use': False},
 'ferrage': {'id': 'ferrage',
             'label': 'Ferrage',
             'type': 'service',
             'family': 'soins_equins',
             'base_price': 1.5,
             'weight': 0,
             'utility': 180,
             'fractionable': False,
             'perishable': False,
             'saturation': 0,
             'production_place': '',
             'savings_use': False},
 'soins_equestres': {'id': 'soins_equestres',
                     'label': 'Soins équestres',
                     'type': 'service',
                     'family': 'soins_equins',
                     'base_price': 3,
                     'weight': 0,
                     'utility': 300,
                     'fractionable': False,
                     'perishable': False,
                     'saturation': 0,
                     'production_place': '',
                     'savings_use': False},
 'soin_blessure': {'id': 'soin_blessure',
                   'label': 'Soin blessure',
                   'type': 'service',
                   'family': 'medecine',
                   'base_price': 2,
                   'weight': 0,
                   'utility': 0,
                   'fractionable': True,
                   'perishable': False,
                   'saturation': 'elevee',
                   'production_place': '',
                   'savings_use': False},
 'soin_blessure_grave': {'id': 'soin_blessure_grave',
                         'label': 'Soin blessure grave',
                         'type': 'service',
                         'family': 'medecine',
                         'base_price': 8,
                         'weight': 0,
                         'utility': 0,
                         'fractionable': True,
                         'perishable': False,
                         'saturation': 'elevee',
                         'production_place': '',
                         'savings_use': False},
 'soin_maladie': {'id': 'soin_maladie',
                  'label': 'Soin maladie',
                  'type': 'service',
                  'family': 'medecine',
                  'base_price': 12,
                  'weight': 0,
                  'utility': 0,
                  'fractionable': True,
                  'perishable': False,
                  'saturation': 'elevee',
                  'production_place': '',
                  'savings_use': False}}


def service_definition(service_id):
    return deepcopy(SERVICE_CATALOG[service_id])


def service_default_price(service_id):
    return SERVICE_CATALOG[service_id]["base_price"]


def service_base_utility(service_id):
    return SERVICE_CATALOG[service_id]["utility"]
